[functions]
  node_bundler          = "esbuild"
  external_node_modules = ["razorpay"]   # optional

# --- Razorpay webhook / signature verification -------------
[[redirects]]
  from = "/razorpay-success.html"
  to   = "/razorpay-success.html"
  status = 200          # ← keep this first

[[redirects]]
  from = "/verify-signature"
  to   = "/.netlify/functions/verify-signature"
  status = 200
  force  = true

# ⬇️ keep the SPA catch-all last
[[redirects]]
  from = "/*"
  to   = "/shop-subscription-app.html"
  status = 200
