###################################
# netlify.toml  – final version
###################################

########################
# 1. Build
########################
[build]
  publish   = "."                 # your HTML lives in repo-root
  functions = "netlify/functions" # folder with Lambda files

########################
# 2. Functions options
########################
[functions]
  node_bundler = "esbuild"        # default, but explicit is nice

########################
# 3. Local dev helpers
########################
[dev]
  functions = "netlify/functions" # lets `netlify dev` find them

########################
# 4. Redirect / Rewrites
########################

# --- expose your Lambda under a short path --------------------
[[redirects]]
  from   = "/api/*"                       # e.g.  /api/create-order
  to     = "/.netlify/functions/:splat"   # real Lambda endpoint
  status = 200

# --- OPTIONAL: if you ever want the raw .netlify/functions URL ---
# (Only needed if you suspect your /* rule might swallow it.
#  Most of the time Netlify protects /.netlify/* automatically.)
# [[redirects]]
#   from   = "/.netlify/functions/*"
#   to     = "/.netlify/functions/:splat"
#   status = 200

# --- your existing single-page-app catch-all -------------------
[[redirects]]
  from   = "/*"
  to     = "/shop-subscription-app.html"
  status = 200                        # “rewrite”; keeps URL bar clean

